name: VMVanish
main: erkam2002\Vanish
version: 1.1
author: erkam2002, Edited by Zeao.
api: 3.0.0-ALPHA8
commands:
  vanish:
    description: "Vanish your self"
    aliases: [sv]
permissions:
  vanish.use:
    description: "Vanish use perm"
    default: op
